#!/usr/bin/env python3
"""
Generate summary table of translation and RRO status.

Counts per app and in total:
- total CJK (zh) entries
- CJK → ru (translated)
- ru-only (no zh)
- translated %
"""
import json, os
from pathlib import Path

TRANS_DIR = Path("./translations")
RRO_DIR = Path("./apks_rro_min")

# Skip translation-progress files generated by translate_one.py
APP_SUFFIX = ".json"
PROGRESS_SUFFIX = "_progress.json"


def is_app_json(fname: str) -> bool:
    return fname.endswith(APP_SUFFIX) and not fname.endswith(PROGRESS_SUFFIX)


def find_rro(app_name: str) -> Path | None:
    for pattern in (
        f"{app_name}.apk",
        f"{app_name}_RRO.apk",
        f"{app_name}_Overlay_ru_signed.apk",
        f"{app_name}_Overlay_ru.apk",
    ):
        path = RRO_DIR / pattern
        if path.exists() and path.stat().st_size > 0:
            return path
    return None


# ----- collect ----------------------------------------------------------
apps = []
for fname in sorted(os.listdir(TRANS_DIR)):
    if not is_app_json(fname):
        continue

    app_name = fname.replace(".json", "")
    json_path = TRANS_DIR / fname
    rro = find_rro(app_name)

    try:
        with open(json_path, encoding="utf-8") as fh:
            data = json.load(fh)
    except Exception:
        continue
    if not isinstance(data, list):
        continue

    cjk = 0        # has zh
    ru_only = 0    # has ru but no zh
    cjk_ru = 0     # both zh and ru (translated)

    for e in data:
        has_zh = bool(e.get("zh"))
        has_ru = bool(e.get("ru"))
        if has_zh and has_ru:
            cjk_ru += 1
        elif has_zh:
            cjk += 1
        elif has_ru:
            ru_only += 1

    total_zh = cjk + cjk_ru
    pct = (cjk_ru / total_zh * 100) if total_zh else (100.0 if not data else 0.0)
    fully_translated = cjk == 0 and total_zh > 0  # все zh-записи переведены
    has_rro = rro is not None

    apps.append(
        dict(
            name=app_name,
            cjk=cjk + cjk_ru,   # total entries that have zh
            cjk_only=cjk,        # zh without ru
            ru_only=ru_only,
            cjk_ru=cjk_ru,
            pct=pct,
            fully=fully_translated,
            has_rro=has_rro,
        )
    )

apps.sort(key=lambda x: x["name"])

# ----- print ------------------------------------------------------------
print("=" * 90)
print("Deepal HU Translate — Сводка переводов")
print("=" * 90)
print()
print(
    f"{'Приложение':<35} {'CJK':>5} {'Без ru':>6} {'%':>6} {'RRO':>5}  {'Статус'}"
)
print("-" * 90)

total_apps = 0
total_cjk = 0
total_cjk_ru = 0
fully_count = 0
rro_count = 0

for a in apps:
    total_apps += 1
    total_cjk += a["cjk"]        # all entries with zh
    total_cjk_ru += a["cjk_ru"]  # translated (zh+ru)
    if a["fully"]:
        fully_count += 1
        if a["has_rro"]:
            rro_count += 1

    rro = "✅" if a["has_rro"] else "❌"
    if a["cjk"] == 0 and a["cjk_ru"] == 0 and a["ru_only"] == 0:
        pct_s = "  —"
        status = "(пусто)"
    elif a["fully"]:
        pct_s = " 100"
        status = "✅ переведено"
    elif a["cjk_ru"] == 0:
        pct_s = "   0"
        status = "(нет ru)"
    else:
        pct_s = f"{a['pct']:5.0f}"
        status = f"🔄 {a['cjk_ru']}/{a['cjk']}"
    print(f"{a['name']:<35} {a['cjk']:>5} {a['cjk_only']:>5} {pct_s:>6} {rro:>5}  {status}")

print("=" * 90)
pct_total = total_cjk_ru / total_cjk * 100 if total_cjk else 0
print()
print(f"Всего приложений: {total_apps}")
print(f"CJK-строк (zh): {total_cjk}")
print(f"Переведено CJK→ru: {total_cjk_ru} ({pct_total:.1f}%)")
pct_apps = fully_count/total_apps*100 if total_apps else 0
print(f"Переведено приложений: {fully_count}/{total_apps} ({pct_apps:.1f}%)")
pct_rro = rro_count/fully_count*100 if fully_count else 0
print(f"RRO APK собрано: {rro_count}/{fully_count} ({pct_rro:.1f}%)")

rro_size = sum((p.stat().st_size for p in RRO_DIR.glob("*.apk")), 0) / 1024
print(f"Размер RRO APK: {rro_size:.0f} KB")
print()

# Top 10 biggest remaining work
print("Топ-10 по объёму непереведённого:")
remaining = sorted(
    [
        (
            a["name"],
            a["cjk"] - a["cjk_ru"],
            a["cjk"],
        )
        for a in apps
        if a["cjk"] > 0
    ],
    key=lambda x: x[1],
    reverse=True,
)[:10]
for name, missing, total in remaining:
    print(f"  {name:<32} {missing:4d}/{total:4d} не переведено")

print("=" * 90)
